# Generated by Django 3.2.19 on 2023-05-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt_pessoas', models.IntegerField()),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('mesa_numero', models.IntegerField()),
                ('resp_nome', models.CharField(max_length=100)),
            ],
        ),
    ]
